version: '3.7'

services:
  golden-hammer-ui:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['npm', 'run', 'docker-compose']
    volumes:
      - .:/app
      # - /app/node_modules
      - /dev/null:/dev/null:/app/.git # For git submodules
      - ../golden-hammer-shared:/golden-hammer-shared
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--enable-source-maps --trace-warnings
    ports:
      - '10229:9229'
      - '9000:9000'
