version: '3.7'

services:
  golden-hammer-ui:
    command: 'npx ghui-dev-linked'
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--enable-source-maps --trace-warnings
      - VERBOSE=1
    ports:
      - '10229:10229'
      - '9000:9000'
