version: '3.7'

services:
  golden-hammer-ui:
    build:
      target: development
    volumes:
      - .:/build
      # - /build/node_modules
    environment:
      - NODE_OPTIONS=--enable-source-maps --trace-warnings
    ports:
      - '10229:9229'
      - '9000:9000'
